language: groovy

install:
  - TERM=dumb ./gradlew -q assemble

script:
  - TERM=dumb ./gradlew pTML test integrationTest --stacktrace --daemon

jdk:
  - oraclejdk7
# weird probs with openjdk
#  - openjdk7
